# Generated by Django 4.2.4 on 2023-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('course_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('Diploma', 'Diploma')], max_length=20)),
                ('eligibility', models.TextField(max_length=50)),
                ('entrance_exam', models.CharField(blank=True, max_length=100)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
    ]
