# Generated by Django 4.2.4 on 2023-09-13 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0003_alter_course_college_alter_course_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_reasoning_score', models.PositiveIntegerField(default=0)),
                ('communication_skills_score', models.PositiveIntegerField(default=0)),
                ('quantitative_aptitude_score', models.PositiveIntegerField(default=0)),
                ('analytical_skills_score', models.PositiveIntegerField(default=0)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=50, null=True)),
                ('plus_two_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
