# Generated by Django 4.2.4 on 2023-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_alter_studentassessment_plus_two_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='assessment_status',
            field=models.BooleanField(default=False),
        ),
    ]
