# Generated by Django 4.2.5 on 2023-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_studentassessment_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
