# Generated by Django 4.2.4 on 2023-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0006_alter_oncourse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncourse',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Web_Development', 'Web_Development'), ('Cybersecurity', 'Cybersecurity'), ('Cloud_Computing', 'Cloud_Computing'), ('Machine_Learning', 'Machine_Learning'), ('Data_Science', 'Data_Science'), ('DevOps', 'DevOps')], default='None', max_length=100),
        ),
    ]
