# Generated by Django 4.2.4 on 2023-09-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0010_alter_oncourse_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncourse',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseprovider.oncourse')),
            ],
        ),
    ]
