# Generated by Django 4.2.4 on 2023-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0013_oncourse_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncourse',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
