# Generated by Django 4.2.4 on 2023-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0014_alter_oncourse_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncourse',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oncourse',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
