# Generated by Django 4.2.5 on 2023-09-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseprovider.oncourse'),
        ),
    ]
