# Generated by Django 4.2.5 on 2023-09-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0017_payment_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_title',
            new_name='course',
        ),
    ]
