# Generated by Django 4.2.5 on 2023-09-27 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseprovider', '0018_rename_course_title_payment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('instructor', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('positions', models.PositiveIntegerField()),
                ('internship_type', models.CharField(choices=[('unpaid', 'Unpaid')], default='unpaid', max_length=20)),
                ('internship_mode', models.CharField(choices=[('online', 'Online')], default='online', max_length=20)),
                ('application_deadline', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web_Development', 'Web_Development'), ('Cybersecurity', 'Cybersecurity'), ('Cloud_Computing', 'Cloud_Computing'), ('Machine_Learning', 'Machine_Learning'), ('Data_Science', 'Data_Science'), ('DevOps', 'DevOps')], default='Programming', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='internship_thumbnails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
