# Generated by Django 4.2.5 on 2023-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0020_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
