# Generated by Django 4.2.5 on 2023-10-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0023_uservideoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideoprogress',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courseprovider.oncourse'),
            preserve_default=False,
        ),
    ]
