# Generated by Django 4.2.5 on 2023-10-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0032_remove_uservideoprogress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseprovider.oncourse'),
        ),
    ]
