# Generated by Django 4.2.5 on 2024-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0038_payment_mentorsupportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsupportsession',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
