# Generated by Django 4.2.5 on 2024-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0041_rename_pplatform_webinar_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='benefits',
        ),
        migrations.AddField(
            model_name='webinar',
            name='selected_benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
