# Generated by Django 4.2.5 on 2024-02-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0044_payment_webinar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
