# Generated by Django 4.2.5 on 2024-02-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0045_alter_payment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
