# Generated by Django 4.2.5 on 2024-02-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0046_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('KEAM', 'KEAM'), ('NEET', 'NEET'), ('JEE', 'JEE')], max_length=50)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('question_paper', models.FileField(upload_to='question_papers/')),
                ('solution', models.FileField(blank=True, null=True, upload_to='solutions/')),
            ],
        ),
    ]
