from django.contrib import admin
from .models import Courseprovider_profile,Mentor_profile,Oncourse,Video,Payment,Internship,UserVideo,Certificate,MentorSupportSession,Webinar,Benefit,QuestionPaper,Review
admin.site.register(Courseprovider_profile)
admin.site.register(Mentor_profile)
admin.site.register(Oncourse)
admin.site.register(Video)
admin.site.register(Payment)
admin.site.register(Internship)
admin.site.register(UserVideo)
admin.site.register(Certificate)
admin.site.register(MentorSupportSession)
admin.site.register(Webinar)
admin.site.register(Benefit)
admin.site.register(QuestionPaper)
admin.site.register(Review)