# Generated by Django 4.2.4 on 2023-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'course_provider'), (3, 'mentor')], default='1', null=True),
        ),
    ]
