# Generated by Django 4.2.4 on 2023-09-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
