# Generated by Django 4.2.5 on 2024-03-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'course_provider'), (3, 'mentor'), (4, 'admin'), (5, 'Editor')], default='1', null=True),
        ),
    ]
