# Generated by Django 4.2.4 on 2023-09-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseprovider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oncourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='thumbnail/')),
                ('video', models.FileField(default='', null=True, upload_to='videos/')),
                ('course_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('duration', models.PositiveIntegerField()),
                ('instructor', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
