# Generated by Django 4.2.4 on 2023-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0012_video_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncourse',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Is Free'),
        ),
    ]
