# Generated by Django 4.2.5 on 2023-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0026_completioncertificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
