# Generated by Django 4.2.5 on 2024-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0036_mentorsupportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsupportsession',
            name='passcode',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
