# Generated by Django 4.2.5 on 2024-01-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseprovider', '0040_benefit_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='pplatform',
            new_name='platform',
        ),
    ]
