# Generated by Django 4.2.4 on 2023-09-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile',
        ),
    ]
