# Generated by Django 4.2.4 on 2023-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_profile_pic_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'course_provider'), (3, 'mentor'), (4, 'admin')], default='1', null=True),
        ),
    ]
