# Generated by Django 4.2.4 on 2023-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_alter_course_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.CharField(max_length=20),
        ),
    ]
